//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long id { get; set; }
        public string fields { get; set; }
        public long company_id { get; set; }
        public string number { get; set; }
        public Nullable<double> totalSum { get; set; }
        public Nullable<double> totalTaxSum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
